In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_customers_dataset.csv")
geolocation = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_geolocation_dataset.csv")
order_items = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_order_items_dataset.csv")
payments = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_order_payments_dataset.csv")
reviews = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_order_reviews_dataset.csv")
orders = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_orders_dataset.csv")
products = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_products_dataset.csv")
sellers = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\olist_sellers_dataset.csv")
category_translation = pd.read_csv(r"C:\Users\ayush\OneDrive\Data analysis project\E-Commerce Customer Intelligence & Business Analytics\Raw Data\product_category_name_translation.csv")

In [3]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [5]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

In [6]:
customers.shape, geolocation.shape, order_items.shape, payments.shape, reviews.shape, orders.shape, products.shape, sellers.shape, category_translation.shape

((99441, 5),
 (1000163, 5),
 (112650, 7),
 (103886, 5),
 (99224, 7),
 (99441, 8),
 (32951, 9),
 (3095, 4),
 (71, 2))

In [7]:
for name, df in tables.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())

============================================================
customers
============================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
geolocation
============================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
order_items
============================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
payments
============================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
reviews
============================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
orders
============================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
products
============================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
sellers
============================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
category_translation
============================================================
['product_category_name', 'product_category_name_english']

In [8]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [9]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [10]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                101385 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [11]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       30719 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            29654 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [12]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         94537 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [13]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [14]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [15]:
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [16]:
category_translation.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [17]:
print("Customer IDs:", customers["customer_id"].nunique(), "/", len(customers))
print("Order IDs:", orders["order_id"].nunique(), "/", len(orders))
print("Product IDs:", products["product_id"].nunique(), "/", len(products))
print("Seller IDs:", sellers["seller_id"].nunique(), "/", len(sellers))

Customer IDs: 99441 / 99441
Order IDs: 99441 / 99441
Product IDs: 32951 / 32951
Seller IDs: 3095 / 3095

In [18]:
print(
    "Orders with unknown customers:",
    (~orders["customer_id"].isin(customers["customer_id"])).sum()
)

Orders with unknown customers: 0

In [19]:
print(
    "Order items with unknown orders:",
    (~order_items["order_id"].isin(orders["order_id"])).sum()
)

print(
    "Order items with unknown products:",
    (~order_items["product_id"].isin(products["product_id"])).sum()
)

print(
    "Order items with unknown sellers:",
    (~order_items["seller_id"].isin(sellers["seller_id"])).sum()
)

Order items with unknown orders: 0
Order items with unknown products: 0
Order items with unknown sellers: 0

In [20]:
for name, df in tables.items():
    print(name, "duplicate rows:", df.duplicated().sum())

customers duplicate rows: 0
geolocation duplicate rows: 261831
order_items duplicate rows: 0
payments duplicate rows: 0
reviews duplicate rows: 0
orders duplicate rows: 0
products duplicate rows: 0
sellers duplicate rows: 0
category_translation duplicate rows: 0

In [21]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [22]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [23]:
geolocation["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [24]:
geolocation["geolocation_zip_code_prefix"].value_counts().head(10)

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

# products

In [25]:
print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       30719 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            29654 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None

In [26]:
print(products.describe())

       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      29654.000000       32949.000000       32949.000000
mean        2285.890268          30.815078          16.937661
std         4307.494323          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000